name: Update File on Form Submission

on:
  push:
    branches:
      - main  # ajuste de acordo com o nome da sua branch principal

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to update file
        run: update-file.js  # ajuste o nome do script conforme necessário
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
